CREATE USER iod WITH PASSWORD 'iod';
CREATE USER grafanareader WITH PASSWORD 'grafanareader';

CREATE DATABASE iod;
GRANT ALL PRIVILEGES ON DATABASE iod TO iod;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO grafanareader;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO grafanareader;